data_csv_path : data/ATP_tweaked.csv

features_to_drop : ["tourney_name", "tourney_id", "p2_name", "p1_name", "p2_id", "p1_id"]
features_to_fill_by_median_per_player : [[f"p{p}_1stIn", f"p{p}_1stWon", 
              f"p{p}_2ndWon", f"p{p}_SvGms", 
              f"p{p}_ace", f"p{p}_bpFaced", 
              f"p{p}_bpSaved", f"p{p}_df", 
              f"p{p}_svpt", f"p{p}_rank", 
              f"p{p}_rank_points", f"p{p}_age", 
              f"p{p}_ht"] for p in range(1,3)]
features_to_fill_by_median : features_to_fill_by_median_per_player[0] + features_to_fill_by_median_per_player[1] + ["minutes"]

features_to_fill_by_new_category : [f"p1_seed", f"p1_entry", f"p2_seed", f"p2_entry"]
